http:
 listner:
   host: "localhost"
   port: "8082"
   path: "/travelonTip/{serviceType}"
db:
 mysql:
   host: "localhost"
   port: "3306"
   user: "root"
   password: "Aswini@2502"
   database: "test_demo"